# This file was generated by GoReleaser. DO NOT EDIT.
class Minidoc < Formula
  desc "mini document manager"
  homepage "https://github.com/7onetella/minidoc"
  version "0.1.10"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/7onetella/minidoc/releases/download/v0.1.10/minidoc_0.1.10_Darwin_x86_64.tar.gz"
    sha256 "75451f7fcd6ee295f64a42750b02ea191d6efc4b3e10c532ccf7c6838efda3a5"
  elsif OS.linux?
  end

  def install
    bin.install "minidoc"
  end
end
