# This file was generated by GoReleaser. DO NOT EDIT.
class Minidoc < Formula
  desc "mini document manager"
  homepage "https://github.com/7onetella/minidoc"
  version "0.1.4"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/7onetella/minidoc/releases/download/v0.1.4/minidoc_0.1.4_Darwin_amd64.tar.gz"
    sha256 "5a7fe343960c2a65cfde1b944fc5b7a0d1f6547c5012dc995b18777040c59927"
  elsif OS.linux?
  end

  def install
    bin.install "minidoc"
  end
end
