# This file was generated by GoReleaser. DO NOT EDIT.
class Minidoc < Formula
  desc "mini document manager"
  homepage "https://github.com/7onetella/minidoc"
  version "0.1.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/7onetella/minidoc/releases/download/v0.1.12/minidoc_0.1.12_Darwin_x86_64.tar.gz"
    sha256 "4baf01c0962cb862d087d94bb2d6bdfe92cabcd2e46b43e275b5d874e29e566b"
  elsif OS.linux?
  end

  def install
    bin.install "minidoc"
  end
end
